export const GET_INSURANCE_CATE = 'GET_INSURANCE_CATE';
export const GET_INSURANCE_CATE_NAME_LIST = 'GET_INSURANCE_CATE_NAME_LIST';
export const GET_BANNER = 'GET_BANNER';
export const GET_NEWS_CATE = 'GET_NEWS_CATE';
